app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::get('/', function () {
    return view('welcome');
});

Route::resource('recipe', 'RecipeController');
Route::resource('ingredient', 'IngredientController');
Route::resource('step', 'StepController');

Route::get('recipe/{recipe}/editingredients', ['as' => 'recipe.editIngredients', 'uses' => 'RecipeController@editIngredients']);

app/Ingredient.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Ingredient extends Model
{
    public function recipes()
    {
        return $this->belongsToMany('App\Recipe')->withPivot('quantity');
    }
}

app/Recipe.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Recipe extends Model
{
    protected $fillable = ['name', 'published', 'pub_date'];
    
    public function steps()
    {
        return $this->hasMany('App\Step');
    }
    
    public function ingredients()
    {
        return $this->belongsToMany('App\Ingredient');
    }
}

app/Step.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Step extends Model
{
    protected $fillable = ['body'];
    
    public function recipe()
    {
        return $this->belongsTo('App\Recipe');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

abstract class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/IngredientController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class IngredientController extends Controller
{
    public function index(Request $request)
    {
        
    }
    
    public function create(Request $request)
    {
        
    }
    
    public function store(Request $request)
    {
        
    }
    
    public function edit(Request $request)
    {
        
    }
    
    public function destroy(Request $request)
    {
        
    }
}

app/Http/Controllers/RecipeController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Recipe;
use App\Ingredient;
use App\Step;
use App\Http\Requests;
use App\Http\Controllers\Controller;
use App\Repositories\RecipeRepository;
use App\Http\Requests\StoreRecipeRequest;
use Session;
use Image;
use Log;
use Input;
use DB;
use Auth;

class RecipeController extends Controller
{
    protected $recipes;

    public function __construct(RecipeRepository $recipes)
    {
        //$this->middleware('auth');
        $this->recipes = $recipes;
    }
    
    public function index(Request $request)
    {
        $results = Recipe::paginate(50);

        return view('recipes.index')
            ->with('recipes', $results->appends(Input::except('page')));
    }
    
    public function show(Request $request, Recipe $recipe)
    {
        return view('recipes.show')
            ->with('recipe', $recipe);
    }

    public function create(Request $request)
    {
    	$ingredient_list = Ingredient::orderBy('name')->get()->lists('name', 'id');
        return view('recipes.create')->with('ingredient_list', $ingredient_list);
    }
    
    public function store(StoreRecipeRequest $request)
    {
        $recipe = new Recipe($request->all());
        $recipe->save();
        
        if (Input::has('ingredient')) {
            /*$recipe->ingredients()->sync(Input::get('ingredient_id'));*/
            foreach(Input::get('ingredient') as $ingredient)
            {
                $recipe->ingredients()->attach($ingredient['id'], ['quantity' => $ingredient['quantity']]);
            }
        }
        
        if (Input::has('step')) {
            foreach(Input::get('step') as $step)
            {
                $new_step = new Step(array('body' => $step));
                $new_step->recipe_id = $recipe->id;
                $new_step->save();
            }
        }
        
        Session::flash('message', 'Recipe created');
        return redirect()->route('recipe.show', array($recipe->id));
    }
    
    public function editIngredients(Request $request, Recipe $recipe)
    {
        return view('recipe.editIngredients')
            ->with('recipe', $recipe);
    }
}

app/Http/Controllers/StepController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;

class StepController extends Controller
{
    public function index(Request $request)
    {
        
    }
    
    public function create(Request $request)
    {
        
    }
    
    public function store(Request $request)
    {
        
    }
    
    public function edit(Request $request)
    {
        
    }
    
    public function destroy(Request $request)
    {
        
    }
}

resources/views/common/errors.blade.php
@if (count($errors) > 0)
        <!-- Form Error List -->
<div class="alert alert-danger">
    <strong>Whoops! Something went wrong!</strong>

    <br><br>

    <ul>
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    </ul>
</div>
@endif

resources/views/common/flash.blade.php
@if(Session::has('message'))
<p class="alert alert-info">{{ Session::get('message') }}</p>
@endif

resources/views/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="it">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>cookingfortwo.it - Administration</title>

    <!-- Bootstrap Core CSS -->
    <link href="/assets/css/admin_layout/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="/assets/css/admin_layout/sb-admin.css" rel="stylesheet">
    <link href="/assets/css/admin_layout/custom.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="/assets/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    
    <link href="/assets/js/admin_layout/jquery-ui/jquery-ui.css" rel="stylesheet" type="text/css">
    

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <div id="wrapper">

        <!-- Navigation -->
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="/admin">cookingfortwo.it - Administration</a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    @if (!Auth::guest())
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ Auth::user()->name }} <b class="caret"></b></a>
                    @endif
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="/auth/logout"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <!--<li>
                        <a href="\admin"><i class="fa fa-fw fa-dashboard"></i> Dashboard</a>
                    </li> -->
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#recipes"><i class="fa fa-fw fa-book"></i> Recipes <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="recipes" class="collapse">
                            <li>
                                <a href="{{ route('recipe.index') }}">List</a>
                            </li>
                            <li>
                                <a href="{{ route('recipe.create') }}">New recipe</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#ingredients"><i class="fa fa-fw fa-pencil"></i> Ingredients <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="ingredients" class="collapse">
                            <li>
                                <a href="{{ route('ingredient.index') }}">List</a>
                            </li>
                            <li>
                                <a href="{{ route('ingredient.create') }}">New ingredient</a>
                            </li>
                        </ul>
                    </li>
 
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>

        <div id="page-wrapper">

            <div class="container-fluid">
                
                @yield('content')

            </div>
            <!-- /.container-fluid -->

        </div>
        <!-- /#page-wrapper -->

    </div>
    <!-- /#wrapper -->

    <!-- jQuery -->
    <script src="/assets/plugins/jquery/jquery.min.js"></script>
    <script src="/assets/js/admin_layout/jquery-ui/jquery-ui.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="/assets/js/admin_layout/bootstrap.min.js"></script>
    
    <script src="/assets/js/admin_layout/custom.js"></script>
    
    <script src="/assets/js/admin_layout/jquery.tablesorter/jquery.tablesorter.js"></script>
    
    <script>
        $(document).ready(function() 
            { 
                $("#admintable").tablesorter({sortList: [[3,1], [0,1]]}); 
            } 
        ); 
    
    </script>

</body>

</html>

resources/views/recipes/create.blade.php
@extends('layouts.admin')

@section('content')
    {!! HTML::script('assets/plugins/ckeditor/ckeditor.js') !!}
    <!-- Page Heading -->
    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                New recipe
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/admin">Admin</a>
                </li>
                <li>
                    <i class="fa fa-book"></i>  <a href="/recipe">Recipes</a>
                </li>
                <li class="active">
                    <i class="fa fa-plus-circle"></i> New Recipe
                </li>
            </ol>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-12">
            <!-- Display Validation Errors -->
            @include('common.errors')
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Insert recipe data</h3>
                </div>
                <div class="panel-body">
                    {!! Form::open(array('action' => 'RecipeController@store', 'files'=>true, 'class' => 'form-horizontal')) !!}
                        
                        <div class="form-group">
                            {!! Form::label('recipe-ingredient-0', 'Ingredient', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('ingredient[0][quantity]', null, array('class' => 'form-control')) !!}
                                {!! Form::select('ingredient[0][id]', $ingredient_list, null, ['class' => 'col-sm-3 form-control']) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-ingredient-1', 'Ingredient', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('ingredient[1][quantity]', null, array('class' => 'form-control')) !!}
                                {!! Form::select('ingredient[1][id]', $ingredient_list, null, ['class' => 'col-sm-3 form-control']) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-ingredient-2', 'Ingredient', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('ingredient[2][quantity]', null, array('class' => 'form-control')) !!}
                                {!! Form::select('ingredient[2][id]', $ingredient_list, null, ['class' => 'col-sm-3 form-control']) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-name', 'Name (*)', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('name', Input::old('name'), array('class' => 'form-control')) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-pub_date', 'Publication date', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('pub_date', Input::old('pub_date'), array('id' => 'datepicker', 'class' => 'form-control')) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-published', 'Published', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::checkbox('published', 1, Input::old('published')) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-step1', 'Step 1', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::textarea('step[0]', Input::old('step[0]'), array('class' => 'form-control ckeditor', 'rows' => 4, 'cols' => 50)) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-step2', 'Step 2', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::textarea('step[1]', Input::old('step[0]'), array('class' => 'form-control ckeditor', 'rows' => 4, 'cols' => 50)) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-step3', 'Step 3', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::textarea('step[2]', Input::old('step[2]'), array('class' => 'form-control ckeditor', 'rows' => 4, 'cols' => 50)) !!}
                            </div>
                        </div>
                        
                        <div class="form-group">
                            {!! Form::label('recipe-step4', 'Step 4', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::textarea('step[3]', Input::old('step[3]'), array('class' => 'form-control ckeditor', 'rows' => 4, 'cols' => 50)) !!}
                            </div>
                        </div>
    
                        <div class="form-group">
                            <div class="col-sm-offset-3 col-sm-6">
                            <a class="btn btn-default btn-close" href="{{ route('recipe.index') }}">Annulla</a>
                            {!! Form::submit('Save', array('class' => 'btn btn-default')) !!}
                            </div>
                        </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/recipes/index.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Page Heading -->
    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                Recipe management
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/admin">Admin</a>
                </li>
                <li class="active">
                    <i class="fa fa-book"></i> Recipes
                </li>
            </ol>
        </div>
    </div>
    <!-- /.row -->
    
     <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Search recipe</h3>
                </div>
                <div class="panel-body">
                    {!! Form::open(array('action' => 'RecipeController@index', 'class' => 'form-horizontal', 'method' => 'GET')) !!}
                        
                        <div class="form-group">
                            {!! Form::label('recipe-name', 'Name', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::text('name', Input::old('name'), array('class' => 'form-control')) !!}
                            </div>
                        </div>

                        <div class="form-group">
                            {!! Form::label('order-by', 'Order by', array('class' => 'col-sm-3 control-label')) !!}
                            <div class="col-sm-6">
                                {!! Form::select('order_by', ['name' => 'Name', 'recipe_pub_date' => 'Pub date'], Input::old('order_by'), ['class' => 'col-sm-3 form-control']) !!}
                            </div>
                        </div>
                        <div class="form-group">
                        <div class="col-sm-offset-3 col-sm-6">
                        {!! Form::submit('Search', array('class' => 'btn btn-default')) !!}
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    <!-- /.row -->
    
    @if (count($recipes) > 0)
    <div class="row">
        <div class="col-sm-12">
            <!-- Display Validation Errors -->
            @include('common.errors')

            <!-- Display Flash Messages -->
            @include('common.flash')
            
            <div class="table-responsive">
                <br>
                <table id="admintable" class="table table-bordered table-hover table-striped tablesorter">
                    <thead>
                        <tr>
                            <th>Name</th>
                            <th>Pub Date</th>
                            <th>Pub</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($recipes as $recipe)
                        <tr> 
                            <td class="table-text">
                                <div>{{ $recipe->name }}</div>
                            </td>
                            
                            <td class="table-text text-center">
                                {{ $recipe->pub_date }}
                            </td>
                            <td class="table-text text-center">
                                @if($recipe->published)
                                    <div><i class="fa fa-check"></i></div>
                                @else
                                    <div><i class="fa fa-times"></i></div>
                                @endif
                            </td>
                            <td>
                                <div class="btn-group">
                                    {!! link_to_route('recipe.show', 'Edit', array('id' => $recipe->id), array('class' => 'btn btn-primary btn-sm')) !!}
                                </div>
                                <form action="/recipe/{{ $recipe->id }}" method="POST" style = "display: inline;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                {!! $recipes->render() !!} 
            </div>
        </div>
    </div>
    <!-- /.row -->
    @endif
@endsection

resources/views/recipes/show.blade.php
@extends('layouts.admin')

@section('content')
    <!-- Page Heading -->
    <div class="row">
        <div class="col-sm-12">
            <h1 class="page-header">
                {{ $recipe->name }}
            </h1>
            <ol class="breadcrumb">
                <li>
                    <i class="fa fa-dashboard"></i>  <a href="/admin">Admin</a>
                </li>
                <li>
                    <i class="fa fa-book"></i>  <a href="/book">Recipes</a>
                </li>
                <li class="active">
                    <i class="fa fa-edit"></i> {{ $recipe->name }}
                </li>
            </ol>
        </div>
    </div>
    
    <div class="row">
        <!-- Display Flash Messages -->
        @include('common.flash')
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Recipe data</h3>
                </div>
                <div class="panel-body">
                    <div><strong>Name:</strong> <br> <span>{{ $recipe->name }}</span></div><br>
                    <div><strong>Pub. date:</strong> <br> <span> {{ $recipe->pub_date  or "-" }}</span></div><br>
                    <div><strong>Published:</strong> <br> <span> {{ ($recipe->published) ? 'YES' : 'NO'  }}</span></div><br>
                    <div>{!! link_to_route('recipe.edit', 'Edit', array('id' => $recipe->id), array('class' => 'btn btn-primary btn-sm')) !!}</div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">Ingredients</h3>
                </div>
                <div class="panel-body">
                    @foreach ($recipe->ingredients as $ingredient)
                        <div><span>{{ $ingredient->name  or "-"  }}</span></div><br> 
                    @endforeach
                    <div>{!! link_to_route('recipe.editIngredients', 'Edit', array('recipe' => $recipe->id), array('class' => 'btn btn-primary btn-sm')) !!}</div>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row">
        <div class="col-sm-12">
            <div class="table-responsive">
                <h3>Steps</h3>
                <table class="table table-bordered table-hover table-striped">
                    <thead>
                        <tr>
                            <th>Body</th>
                            <th>&nbsp;</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($recipe->steps as $step)
                        <tr> 
                            <td class="table-text">
                                <div>{{ $step->body }}</div>
                            </td>

                            <td>
                                <div class="btn-group">
                                    {!! link_to_route('step.edit', 'Edit', array('recipe' => $recipe->id, 'step' => $step->id), array('class' => 'btn btn-primary btn-sm')) !!}
                                </div>
                                <form action="/step/{{ $step->id }}" method="POST" style = "display: inline;">
                                    {{ csrf_field() }}
                                    {{ method_field('DELETE') }}
                                    <button class="btn btn-danger btn-sm">Delete</button>
                                </form>
                            </td>
                        </tr>
                    @endforeach
                    </tbody>
                </table>
                <div>
                    {!! link_to_route('step.create', 'Add step', array('id' => $recipe->id), array('class' => 'btn btn-primary btn-sm')) !!}
                </div>
            </div>
        </div>
    </div>
@endsection